# Generated by Django 5.1.1 on 2024-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
