# Generated by Django 5.1.1 on 2024-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_updating',
            field=models.BooleanField(default=False),
        ),
    ]
