# Generated by Django 5.1.1 on 2024-10-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_updating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_updating',
        ),
    ]
